<a href="https://colab.research.google.com/github/mrozik1141/Machine_Leaning/blob/main/Numpy_datascience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.26.4'

In [ ]:
x= np.array([1,3])
print(x.shape)
print(x.ndim)
print(x.size)
print(x.dtype)

(2,)
1
2
int64


In [ ]:
y = np.array([[1,2],[3,4]])
print(y)
print(y.ndim)
print(y.shape)
print(y.size)

[[1 2]
 [3 4]]
2
(2, 2)
4


In [ ]:
z = np.array(
    [[[1,2,3],[3,4,5]],[[-1,2,-4],[7,6,2]]])
z

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[-1,  2, -4],
        [ 7,  6,  2]]])

In [ ]:
z.ndim

3

In [ ]:
z.shape

(2, 2, 3)

In [ ]:
np.zeros(shape=(3,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(2,5,1))

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype="int")

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])



In [ ]:
A + B


array([6, 0, 7, 4])

In [ ]:
A-B

array([0, 2, 1, 0])

In [ ]:
A*B

array([ 9, -1, 12,  4])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
2*A

array([6, 2, 8, 4])

In [ ]:
np.add(A,B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [ ]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
X=np.array([[1,3],[-2,0]])
Y= np.array([[6,0],[-1,2]])
print(X)
print(Y)


[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [ ]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [ ]:
Y@X

array([[ 6, 18],
       [-5, -3]])

In [ ]:
np.random.seed(0)

In [ ]:

np.random.randn(10,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275]])

In [ ]:
np.random.rand(10,2)

array([[0.31542835, 0.36371077],
       [0.57019677, 0.43860151],
       [0.98837384, 0.10204481],
       [0.20887676, 0.16130952],
       [0.65310833, 0.2532916 ],
       [0.46631077, 0.24442559],
       [0.15896958, 0.11037514],
       [0.65632959, 0.13818295],
       [0.19658236, 0.36872517],
       [0.82099323, 0.09710128]])

In [ ]:
np.random.randint(low=10, high=100, size=(3,3))

array([[60, 46, 44],
       [58, 13, 52],
       [87, 31, 83]])

In [ ]:
np.random.choice(['python','java','sql'])

'sql'

In [ ]:
data= np.arange(10)

In [ ]:
np.random.shuffle(data)
data

array([3, 9, 2, 8, 1, 7, 6, 0, 5, 4])